apiVersion: v1
kind: ConfigMap
metadata:
  name: html-config
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
        <title>Web Server</title>
    </head>
    <body>
        <h1>Welcome to the Web Server</h1>
        <p>Serving Host: serving-host</p>
    </body>
    </html>
