replicas: 3
nodePort: 30080
nginxImage: nginx:1.14.2
resources:
  requests:
    memory: "256Mi"
    cpu: "250m"
  limits:
    memory: "512Mi"
    cpu: "500m"
ingress:
  groupName: ng-group
  scheme: internet-facing
