apiVersion: v1
kind: Service
metadata:
  name: web-server-service
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: web-server
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    # nodePort: {{ .Values.nodePort }}
